export default [
  //Home
  {
    path:'/home',
    name:'home.index',
    component: () => import('@/views/Home/Index.vue'),
    meta:{
      guest:true
    }
  },
  {
    path:'/apply',
    name:'apply.index',
    component: () => import('@/views/Apply/Index.vue'),
    meta:{
      guest:true
    }
  },
  {
    path:"/domain",
    name:"domain.layout",
    component:()=> import('@/views/Domain/Layout.vue'),
    children:[
      {
        path:"regist",
        name:"domain.regist",
        component:()=>import('@/views/Domain/Regist.vue'),
        meta:{
          guest:true
        }
      },
      {
        path:"registsub",
        name:"domain.registsub",
        component:()=>import('@/views/Domain/RegistSub.vue'),
        meta:{
          guest:true
        }
      },
      {
        path:"registing",
        name:"domain.registing",
        component:()=>import('@/views/Domain/Registing.vue'),
        meta:{
          guest:true
        }
      },
      {
        path:"detail/:id",
        name:"domain.detail",
        component:()=>import('@/views/Domain/DetailInfo.vue'),
        meta:{
          guest:true
        }
      },
    ],
    meta:{
      guest:true
    }
  },
  {
    path:'/market',
    name:'market.layout',
    redirect:'/market/index',
    component: ()=> import('@/views/Market/Layout.vue'),
    children:[
      {
        path:"index",
        name:"market.index",
        redirect:'/market/index/latest',
        component:()=>import('@/views/Market/Index.vue'),
        meta:{
          guest:true
        },
        children:[
          {
            path:'latest',
            name:'market.index.latest',
            component:()=>import('@/views/Market/LatestTransactions.vue'),
            meta:{
              guest:true
            },
          }
        ]
      }

    ],
    meta: {
      guest:true
    }
  },
  {
    path:'/agent',
    name:'agent.index',
    component: ()=> import('@/views/SuperAgent/Index.vue'),
    meta: {
      guest:true
    }
  },
  {
    path:'/owner/:id',
    name:'owner.info',
    component: ()=> import('@/views/Domain/OwnerInfo.vue'),
    meta: {
      guest:true
    }
  },
  {
    path:'/account',
    name:'account.index',
    component: () => import('@/views/Account/Index.vue'),
    meta:{
      // auth:true,
      guest:true,
    }
  },
  {
    path:'/download',
    name:'download.index',
    component:() => import('@/views/Download/Index.vue'),
    meta:{
      guest:true
    }
  },
  {
    path:"/help",
    name:"help.layout",
    redirect:'/help/issue',
    component:()=> import('@/views/Help/Layout.vue'),
    meta:{
      guest:true
    },
    children:[
      {
        path:'issue',
        name:'help.issue',
        component:()=>import('@/views/Help/IssueNavigation.vue'),
        meta:{
          guest:true
        },
      },
      {
        path:'buyer',
        name:'help.buyer',
        component:()=>import('@/views/Help/BuyerNavigation.vue'),
        meta:{
          guest:true
        },
      },
      {
        path:'seller',
        name:'help.seller',
        component:()=>import('@/views/Help/SellerNavigation.vue'),
        meta:{
          guest:true
        },
      }
    ]
  },
  {
    path:"/wallet",
    name:"wallet.layout",
    redirect:'/wallet/index',
    component:()=>import('@/views/Wallet/Layout.vue'),
    meta:{
      guest:true
    },
    children:[
      {
        path:'index',
        name:'wallet.index',
        component:()=>import('@/views/Wallet/WalletIndex.vue'),
        meta:{
          guest:true
        },
      },
      {
        path:'transaction',
        name:'wallet.transaction',
        component:()=>import('@/views/Wallet/Intransaction.vue'),
        meta:{
          guest:true
        },
      },
      {
        path:'income',
        name:'wallet.income',
        component:()=>import('@/views/Wallet/DomainIncome.vue'),
        meta:{
          guest:true
        },
      },
    ]
  },
  {
    path:'/login',
    name:'login.index',
    component:() => import('@/views/Login/Index.vue'),
    meta:{
      guest:true
    }
  },
  {
    path:'/',
    redirect:'/home'
  },
  {
    path:'/*',
    redirect:'/home'
  }
]
